name: plannet_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
      - assets/img/mars.png
      - assets/img/earth.png
      - assets/img/ic_distance.png
      - assets/img/ic_gravity.png
      - assets/img/mercury.png
      - assets/img/moon.png
      - assets/img/neptune.png

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400